name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip

    - name: Deploy to Server
      run: |
        pip install fabric
        python deploy.py
